_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.9.13
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.9.13
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
action_size:
    value: 2
batch_size:
    value: 64
buffer_size:
    value: 10000
env_name:
    value: CartPole-v1
eps_decay:
    value: 0.995
eps_end:
    value: 0.01
eps_start:
    value: 1
gamma:
    value: 0.99
hidden_size:
    value: 64
lr:
    value: 0.001
max_steps:
    value: 1000
num_episodes:
    value: 500
state_size:
    value: 4
tau:
    value: 0.001
update_every:
    value: 4
