_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 71
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 71
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.9
            "5": 0.19.6
            "6": 4.50.3
            "8":
                - 3
                - 5
            "12": 0.19.6
            "13": windows-amd64
batch_size:
    value: 32
env_name:
    value: CartPole-v1
gamma:
    value: 1
num_episodes:
    value: 50
num_epochs:
    value: 10
seq_len:
    value: 20
