_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.11.9
            "5": 0.19.6
            "8":
                - 3
                - 5
            "12": 0.19.6
            "13": windows-amd64
algorithm:
    value: decision_transformer
batch_size:
    value: 64
environment:
    value: CartPole-v1
episodes:
    value: 50
epochs:
    value: 30
gamma:
    value: 0.99
hidden_dim:
    value: 256
learning_rate:
    value: 0.0001
num_heads:
    value: 8
num_layers:
    value: 4
seq_len:
    value: 40
