_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.9
            "5": 0.19.6
            "8":
                - 3
                - 5
            "12": 0.19.6
            "13": windows-amd64
action_size:
    value: 2
actor_lr:
    value: 0.001
critic_lr:
    value: 0.001
entropy_coef:
    value: 0.01
env_name:
    value: CartPole-v1
gamma:
    value: 0.99
hidden_size:
    value: 128
max_steps:
    value: 1000
num_episodes:
    value: 1000
state_size:
    value: 4
